#!/usr/bin/env bash

set -e

readonly SH_DIR="$(dirname "${BASH_SOURCE[0]}")"

if [ -n "$1" ]; then
  cd $1
fi

if [ ! -f ./package.json ]; then
  echo "Error: package.json file not found" &>2
  exit 1
fi

"$SH_DIR"/prepare -m development

( npm run build:types ) &

(
  if [ -f scss/style.scss ]; then
    rm -vf dist/style.css
    npx sass scss/style.scss dist/style.css
  fi
) &

(
  if [ -f scss/style.scss ]; then
    rm -vf dist/style.min.css
    npx sass --style=compressed scss/style.scss dist/style.min.css
  fi
) &

for i in esm cjs; do
  (
    rm -vf dist/index.$i.js
    npx esbuild --bundle --packages=external --format=$i \
        --outfile=dist/index.$i.js \
        --sourcemap "src/index.ts"
  ) &

  (
    rm -vf dist/index.$i.min.js
    npx esbuild --bundle --packages=external --format=$i \
        --outfile=dist/index.$i.min.js \
        --sourcemap "src/index.ts" \
        --tree-shaking --minify
  ) &

  wait
done

"$SH_DIR"/prepare -m production
